# Generated by Django 3.2.25 on 2025-06-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Readora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
